### ISSUE TITLE
Voting example at tmagrino/fabric-voting fails to initialize voting state

### ISSUE THREAD

**Issue by anyachopra97** [apl-cornell/fabric#42] opened 2019-07-22 13:52 UTC
After starting the election store and a district store, I tried to run "bin/init-voting-state 1" and got the error message attached.
<img width="526" alt="Screen Shot 2019-07-22 at 9 40 00 AM" src="https://user-images.githubusercontent.com/28516523/61637904-5ab58d00-ac66-11e9-9dea-6500da63230e.png">

**Comment by tmagrino** [comment] 2019-07-22 17:03
Hi @anyachopra97, it looks like you didn't start the district in another terminal before running the initialization script?  I just confirmed that I get this error message when I only start the election server and it goes away if I restart everything (clearing out var) and start district1 before running the initialization script.

**Comment by tmagrino** [comment] 2019-07-22 17:21
Actually, after talking to @anyachopra97 in person, this seems to be another instance of a funny thing with recent OS X versions not resolving 127.0.0.2 or other local addresses correctly.  Changing the node configurations to 127.0.0.1 fixed things.  I'll commit an update to that repo with the change, just to avoid future confusion.

**Closed by tmagrino** 2019-07-22 17:21 UTC
